version: "3"

services:
    app:
        build:
            context: .
        ports:
            - "9080:9080"
        volumes:
            - ./MFA-Project:/MFA-Project
        command: >
              sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:9080"
        environment:
            - DB_HOST=db
            - DB_NAME=app
            - DB_USER=postgres
            - DB_PASS=supersecretpassword
        depends_on:
            - db
    db:
        image: postgres:12-alpine
        environment:
            - POSTGRES_DB=app
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=supersecretpassword
    
        
    
        
